#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

alias emacs-daemon='/usr/local/bin/emacs --daemon'
alias emacs='/usr/local/bin/emacscient -c'
alias em='/usr/local/bin/emacscient -t'
alias mg='mg -n'
alias edit='mg -n'

export EDITOR='mg -n'
export VISUAL='mg -n'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='fr_FR.UTF-8'
fi


#
# Aliases

alias -s pdf="open -a Skim "
alias -s mod="emacs "
alias -s dyn="emacs "
alias -s tikz="emacs "
alias -s tex="emacs "
alias -s m="emacs "
alias -s md="emacs "
alias -s am="emacs "
alias -s log="emacs "
alias -s txt="emacs "

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /Users/stepan/.scripts
  /Users/stepan/dynare/admin-wiki/scripts
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

DISABLE_AUTO_TITLE=true

#
# Compilers
#
export CC=gcc-5
export CXX=g++-5
export FC=gfortran-5


#
#  Matlab/Octave
#
export JAVA_HOME=$(/usr/libexec/java_home)
export MATLAB_HOME=/Applications/MATLAB_R2015b.app
